### ISSUE TITLE
redux not found

### ISSUE THREAD

**Issue by panneer26** [dtanzer/reactjs-jointjs-example#2]
> reactjs-jointjs-example@1.0.0 start /home/cdps/Downloads/reactjs-jointjs-example-master
> watchify app/app.js -t babelify -o public/js/bundle.js --verbose --debug

Error: Cannot find module 'redux' from '/home/cdps/Downloads/reactjs-jointjs-example-master/app'
Error: Cannot find module 'react-redux' from '/home/cdps/Downloads/reactjs-jointjs-example-master/app'
Error: Cannot find module 'react' from '/home/cdps/Downloads/reactjs-jointjs-example-master/app'
Error: Cannot find module 'react-dom' from '/home/cdps/Downloads/reactjs-jointjs-example-master/app'
Error: Cannot find module 'redux-immutable' from '/home/cdps/Downloads/reactjs-jointjs-example-master/app'
{ [Error: ENOENT: no such file or directory, open 'public/js/bundle.js']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'public/js/bundle.js' }
Error: Cannot find module 'react-redux' from '/home/cdps/Downloads/reactjs-jointjs-example-master/app'
Error: Cannot find module 'react' from '/home/cdps/Downloads/reactjs-jointjs-example-master/app'
Error: Cannot find module 'react-redux' from '/home/cdps/Downloads/reactjs-jointjs-example-master/app'
Error: Cannot find module 'react' from '/home/cdps/Downloads/reactjs-jointjs-example-master/app'
Error: Cannot find module 'react-dom' from '/home/cdps/Downloads/reactjs-jointjs-example-master/app/stations'
Error: Cannot find module 'react' from '/home/cdps/Downloads/reactjs-jointjs-example-master/app/stations'
Error: Cannot find module 'react-redux' from '/home/cdps/Downloads/reactjs-jointjs-example-master/app/stations'
Error: Cannot find module 'react' from '/home/cdps/Downloads/reactjs-jointjs-example-master/app/stations'
Error: Cannot find module 'react' from '/home/cdps/Downloads/reactjs-jointjs-example-master/app/stations'

**Comment by dtanzer** [comment]
Did you run `npm install` first?
